config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Discover New Cocktails!</h1>
    <p>Discover and create your  own recipes</p>
    <p>Choose from over 160 ingredients</p>
  </div>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/cocktails/index.html.erb
<%= render "banner" %>
<div class="index-wrapper">
  <div class="container">
    <div class="row">
      <% if @cocktails.count >= 1 %>
        <% @cocktails.each do |cocktail| %>
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
            </p>
          </div>
          <%= link_to cocktail.name, cocktail_path(cocktail) %>
        <% end %>
      <% end %>
      <%= cl_image_tag("v1590156516/ciyftgdml8yxolvw9gw8.jpg",
          width: 400, height: 300, crop: :fill) %>
          <%= cl_image_tag("https://res.cloudinary.com/neeele/image/upload/v1590156545/tqky1gmvy7n10xyasmxp.jpg",
          width: 150, height: 150, crop: :thumb, gravity: :face) %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">
        <h1>Add a new cocktail</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">
        <%= render "form", cocktail: @cocktail %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="show-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
        <h1><%= @cocktail.name %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
        <h3>Ingredients:</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
        <table>
        <% @cocktail.doses.each do |dose| %>
          <% if dose.description == 1 %>
            <tr><td>1 dose of <%= dose.ingredient.name %></td><td><%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Do you really want to delete?"} %></td></tr>
          <% else %>
            <tr><td><%= dose.description %> doses of <%= dose.ingredient.name %></td><td><%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Do you really want to delete?"} %></td></tr>
          <% end %>
        <% end %>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
        <h3 style="font: Arial, font-size:20px">Add an ingredient:</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
        <%= simple_form_for [@cocktail, @dose], html: { class: "form-inline"} do |f| %>
          <%= f.input :description, label: "Amount:", required: false, as: :integer, input_html: { style: 'width: 80px'} %>
          <%= f.association :ingredient, label: "dose(s) of", prompt: "Select an ingredient", collection: Ingredient.order('name ASC'), required: false  %>
          <%= f.button :submit, name: "commit", value: "Add", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description, label: "Amount" %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/doses/_new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h1><%= @cocktail.name %></h1>

<h3>Ingredients:</h3>
<table>
<% @cocktail.doses.each do |dose| %>
  <% if dose.description == "1" %>
    <tr><td>1 dose of <%= dose.ingredient.name %></td><td><%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Do you want to delete?"} %></td></tr>
  <% else %>
    <tr><td><%= dose.description %> doses of <%= dose.ingredient.name %></td><td><%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?"} %></td></tr>
  <% end %>
<% end %>
</table>

<h3>Add a dose:</h3>

<%= simple_form_for [@cocktail, @dose], html: { class: "form-inline"} do |f| %>
  <%= f.input :description, label: "Amount:", required: false, as: :integer, input_html: { style: 'width: 70px'} %>
  <%= f.association :ingredient, label: "dose(s) of&nbsp;".html_safe, prompt: "Select an ingredient", collection: Ingredient.order('name ASC'), required: false  %>
  <%= f.button :submit, name: "commit", value: "Add" %>
<% end %>

<%= link_to "Return to cocktails list", cocktails_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="https://github.com/grisreyesrios/rails-mister-cocktail" target="blank_">Discover the code at GitHub</a>.
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon by Grisell Reyes Rios
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar">
  <%= link_to "Cocktails Menu", root_path %>
  <%= link_to(new_cocktail_path) do %>
    <span id="new_cocktail">New Cocktail</span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>